export const RFAHeaderMap = {
    serial_num: 'Serial Number',
    agency_action_num: 'Agency Action Number',
    bureau: 'Bureau',
    agency: 'Agency',
    main_function_id: 'Main Function Identifier',
    intermediate_function_id: 'Intermediate Function Indentifier',
    detailed_function_id: 'Detailed Function Identifier',
    frequency_khz: 'Frequency',
    frequency: 'Frequency',
    station_class: 'Station Class',
    emission_designator: 'Emission Designator',
    power: 'Power',
    tx_state_country_code: 'Tx State/Country Code',
    tx_antenna_location: 'Tx Antenna Location',
    tx_station_control: 'Tx Station Control',
    tx_station_call_sign: 'Tx Station Call Sign',
    tx_antenna_latitude: 'Tx Antenna Latitude',
    tx_antenna_longitude: 'Tx Antenna Longitude',
    tx_authorized_radius: 'Tx Authorized Radius',
    tx_inclination_angle: 'Tx Inclination Angle',
    tx_apogee: 'Tx Apogee',
    tx_perigee: 'Tx Perigee',
    tx_period_of_orbit: 'Tx Period of Orbit',
    tx_number_of_satellites: 'Tx Number of Satellites',
    tx_power_density: 'Tx Power Density',
    tx_equipment_nomenclature: 'Tx Equipment Nomenclature',
    tx_system_name: 'Tx System Name',
    tx_number_of_stations: 'Tx Number of Stations',
    tx_ots_equipment: 'Tx Off-the-Shelf Equipment',
    tx_radar_tunability: 'Tx Radar Tunability',
    tx_pulse_duration: 'Tx Pulse Duration',
    tx_pulse_repetition_rate: 'Tx Pulse Repetiion Rate',
    tx_antenna_name: 'Tx Antenna Name',
    tx_antenna_nomenclature: 'Tx Antenna Nomenclature',
    tx_antenna_gain: 'Tx Antenna Gain',
    tx_antenna_elevation: 'Tx Antenna Elevation',
    tx_antenna_feed_point_height: 'Tx Antenna Feed Point Height',
    tx_antenna_horizontal_beamwidth: 'Tx Antenna Horizontal Beamwidth',
    tx_antenna_azimuth: 'Tx Antenna Azimuth',
    tx_antenna_orientation: 'Tx Antenna Orientation',
    tx_antenna_polarization: 'Tx Antenna Polarization',
    tx_JSC_area_code: 'Tx JSC Area Code',
    rx_state_country_code: 'Rx State/Country Code',
    rx_antenna_location: 'Rx Antenna Location',
    rx_control_ID_and_server_system_ID: 'Rx Control ID and Server System ID',
    rx_antenna_latitude: 'Rx Antenna Latitude',
    rx_antenna_longitude: 'Rx Antenna Longitude',
    rx_station_call_sign: 'Rx Station Call Sign',
    rx_authorized_radius: 'Rx Authorized Radius',
    rx_repeater_indicator: 'Rx Repeater Indicator',
    rx_inclination_angle: 'Rx Inclination Angle',
    rx_apogee: 'Rx Apogee',
    rx_perigee: 'Rx Perigee',
    rx_period_of_orbit: 'Rx Period of Orbit',
    rx_number_of_satellites: 'Rx Number of Satellites',
    rx_equipment_nomenclature: 'Rx Equipment Nomenclature',
    rx_antenna_name: 'Rx Antenna Name',
    rx_antenna_nomenclature: 'Rx Antenna Nomenclature',
    rx_antenna_gain: 'Rx Antenna Gain',
    rx_antenna_elevation: 'Rx Antenna Elevation',
    rx_antenna_feed_point_height: 'Rx Antenna Feed Point Height',
    rx_antenna_horizontal_beamwidth: 'Rx Antenna Horizontal Beamwidth',
    rx_antenna_azimuth: 'Rx Antenna Azimuth',
    rx_antenna_orientation: 'Rx Antenna Orientation',
    rx_antenna_polarization: 'Rx Antenna Polarization',
    rx_JSC_area_code: 'Rx JSC Area Code',
    last_transaction_date: 'Last Transaction Date',
    revision_date: 'Revision Date',
    authorization_date: 'Authorization Date',
    expiration_date: 'Expiration Date',
    review_date: 'Review Date',
    entry_date: 'Entry Date',
    receipt_date: 'Receipt Date'
};