--Initially, only some columns will be extracted
CREATE TABLE RFAs (
    serial_number text primary key,
    agency_action_number text,
    classification text,
    bureau text,
    agency text,
    record_type text,
    main_function_id text,
    intermediate_function_id text,
    detailed_function_id text,
    irac_docket_number text[],
    docket_number_old text,
    sxxi_frequency text,
    center_frequency numeric,
    bandwidth numeric,
    frequency_band numrange,
    sxxi_frequency_upper_limit text,
    frequency_upper_limit numeric,
    sxxi_excluded_frequency_bands text[],
    excluded_frequency_bands nummultirange,
    sxxi_paired_frequency text[],
    paired_frequency nummultirange,
    gmf_time text,
    timing text,
    irac_notes text[],
    free_text text[],
    misc_agency_data text[],
    fas_agenda text[],
    supplementary_details text,
    point_of_contact text,
    poc_name text,
    poc_phone_number text,
    poc_verification_date date,
    joint_agency_names text[],
    international_coordination_id text,
    canadian_coordination_comments text[],
    mexican_coordination_comments text[],
    user_net_code text[],
    --Emission group
    station_class text[],
    emission_designator text[],
    sxxi_power text[],
    power_w numeric[],
    effective_radiated_power text[],
    power_augmentation text[],
    max_power numeric,
    --Transmitter group
    tx_state_country_code text,
    tx_antenna_location text,
    tx_station_control text,
    tx_station_call_sign text,
    tx_antenna_latitude text,
    tx_antenna_longitude text,
    tx_lat_long text,
    tx_authorized_radius text,
    tx_inclination_angle numeric,
    tx_apogee numeric,
    tx_perigee numeric,
    tx_period_of_orbit text,
    tx_number_of_satellites numeric,
    tx_power_density text, --Will make numeric later
    tx_equipment_nomenclature text[],
    tx_system_name text,
    tx_number_of_stations numeric,
    tx_ots_equipment text,
    tx_radar_tunability text,
    tx_pulse_duration text[],
    tx_pulse_repetition_rate text[],
    tx_antenna_name text,
    tx_antenna_nomenclature text,
    tx_antenna_gain numeric[],
    tx_antenna_elevation numeric,
    tx_antenna_feed_point_height numeric,
    tx_antenna_horizontal_beamwidth numeric,
    tx_antenna_azimuth text,
    tx_antenna_orientation text,
    tx_antenna_polarization text,
    tx_jsc_area_code text,
    --Receiver group
    rx_state_country_code text[],
    rx_antenna_location text[],
    rx_control_id_and_server_system_id text[],
    rx_antenna_latitude text[],
    rx_antenna_longitude text[],
    rx_lat_long text[],
    rx_station_call_sign text[],
    rx_authorized_radius text[],
    rx_repeater_indicator text[],
    rx_inclination_angle numeric[],
    rx_apogee numeric[],
    rx_perigee numeric[],
    rx_period_of_orbit text[],
    rx_number_of_satellites numeric[],
    rx_equipment_nomenclature text[],
    rx_antenna_name text[],
    rx_antenna_nomenclature text[],
    rx_antenna_gain numeric[],
    rx_antenna_elevation numeric[],
    rx_antenna_feed_point_height numeric[],
    rx_antenna_horizontal_beamwidth numeric[],
    rx_antenna_azimuth text[],
    rx_antenna_orientation text[],
    rx_antenna_polarization text[],
    rx_jsc_area_code text[],
    --Area authorization
    authorized_area_both text[],
    rx_authorized_area text[],
    tx_authorized_area text[],
    excepted_states_both text[],
    rx_excepted_states text[],
    tx_excepted_states text[],
    authorized_states_both text[],
    rx_authorized_states text[],
    tx_authorized_states text[],
    --Dates
    last_transaction_date date,
    revision_date date,
    authorization_date date,
    expiration_date date,
    review_date date,
    entry_date date,
    receipt_date date
);

CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");