--Initially, only some columns will be extracted
CREATE TABLE RFAs (
    serial_num text primary key,
    agency_action_num text,
    bureau text,
    agency text,
    main_function_id text,
    intermediate_function_id text,
    detailed_function_id text,
    -- IRAC_docket_num text[],
    frequency text,
    frequency_KHz numeric,
    frequency_upper_limit text,
    excluded_frequency_bands text[],
    -- paired_frequency text[],
    -- GMF_time text,
    -- IRAC_notes text[],
    -- free_text text[],
    -- misc_agency_data text[],
    -- FAS_agenda text[],
    -- supplementary_details text[],
    point_of_contact text,
    -- joint_agency_names text[],
    -- international_coordination_ID text,
    -- Canadian_coordination_comments text[],
    -- Mexican_coordination_comments text[],
    -- user_net_code text[],
    --Emission group
    station_class text[],
    emission_designator text[],
    power text[],
    --Transmitter group
    tx_state_country_code text,
    tx_antenna_location text,
    tx_station_control text,
    tx_station_call_sign text,
    tx_antenna_latitude text,
    tx_antenna_longitude text,
    tx_authorized_radius text,
    tx_inclination_angle text,
    tx_apogee text,
    tx_perigee text,
    tx_period_of_orbit text,
    tx_number_of_satellites text,
    tx_power_density text,
    tx_equipment_nomenclature text[],
    tx_system_name text[],
    tx_number_of_stations text[],
    tx_OTS_equipment text[],
    tx_radar_tunability text,
    tx_pulse_duration text[],
    tx_pulse_repetition_rate text[],
    tx_antenna_name text[],
    tx_antenna_nomenclature text[],
    tx_antenna_gain text[],
    tx_antenna_elevation text[],
    tx_antenna_feed_point_height text[],
    tx_antenna_horizontal_beamwidth text[],
    tx_antenna_azimuth text[],
    tx_antenna_orientation text[],
    tx_antenna_polarization text[],
    tx_JSC_area_code text,
    --Receiver group
    rx_state_country_code text[],
    rx_antenna_location text[],
    rx_control_ID_and_server_system_ID text[],
    rx_antenna_latitude text[],
    rx_antenna_longitude text[],
    rx_station_call_sign text[],
    rx_authorized_radius text[],
    rx_repeater_indicator text[],
    rx_inclination_angle text[],
    rx_apogee text[],
    rx_perigee text[],
    rx_period_of_orbit text[],
    rx_number_of_satellites text[],
    rx_equipment_nomenclature text[],
    rx_antenna_name text[],
    rx_antenna_nomenclature text[],
    rx_antenna_gain text[],
    rx_antenna_elevation text[],
    rx_antenna_feed_point_height text[],
    rx_antenna_horizontal_beamwidth text[],
    rx_antenna_azimuth text[],
    rx_antenna_orientation text[],
    rx_antenna_polarization text[],
    rx_JSC_area_code text[],
    --Area authorization
    -- authorized_area_both text[],
    -- tx_authorized_area text[],
    -- excepted_states_both text[],
    -- rx_excepted_states text[],
    -- tx_excepted_states text[],
    -- authorized_states_both text[],
    -- rx_authorized_states text[],
    -- tx_authorized_states text[],
    --Dates
    last_transaction_date date,
    revision_date date,
    authorization_date date,
    expiration_date date,
    review_date date,
    entry_date date,
    receipt_date date
);